# Generated by Django 5.1.3 on 2024-11-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userwallets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_token', models.CharField(max_length=50)),
                ('quote_token', models.CharField(max_length=50)),
                ('base_token_address', models.CharField(max_length=50)),
                ('quote_token_address', models.CharField(max_length=50)),
                ('created_at_price', models.FloatField()),
                ('created_at_native_price', models.FloatField()),
                ('limit_price', models.FloatField()),
                ('pair_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_token', models.CharField(max_length=50)),
                ('quote_token', models.CharField(max_length=50)),
                ('base_token_address', models.CharField(max_length=50)),
                ('quote_token_address', models.CharField(max_length=50)),
                ('created_at_price', models.FloatField()),
                ('created_at_native_price', models.FloatField()),
                ('sold_price', models.FloatField()),
                ('sold_native_price', models.FloatField()),
                ('pair_address', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminal_api.user')),
            ],
        ),
    ]
