# Generated by Django 5.1.3 on 2024-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terminal_api", "0002_user_is_active_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userwallets",
            name="address",
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name="userwallets",
            name="mnemonic",
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name="userwallets",
            name="private_key",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="userwallets",
            name="public_key",
            field=models.CharField(max_length=64),
        ),
    ]
