# Generated by Django 5.1.4 on 2024-12-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal_api', '0004_pairinfo_remove_order_base_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
