services:
  db:
    image: postgres:14-alpine
    container_name: db
    command: postgres -c 'max_connections=15000'
    shm_size: 512m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  django_terminal:
    container_name: django_terminal
    command: ["bash", "/code/docker/start_server.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
