services:
  terminal_db:
    image: postgres:16-alpine
    container_name: terminal_db
    command: postgres -c 'max_connections=15000'
    shm_size: 512m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    env_file:
      - .env
    profiles:
      - default
      - production

  django_terminal:
    container_name: django_terminal
    command: ["bash", "/code/docker/start_server.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - terminal_db
    profiles:
      - default

  django_terminal_production:
    container_name: django_terminal_production
    command: [ "bash", "/code/docker/start_server_production.sh" ]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    build: .
    restart: unless-stopped
    profiles:
      - production
      - production_only
    env_file:
      - .env
    depends_on:
      - terminal_db

volumes:
  postgres_data:
